### ISSUE TITLE
Deploy and setup CD

### ISSUE THREAD

**Issue by victorb** [ipld/website#11]
We need to have a quick and efficient way of deploying ipld.io when it changes.

depends on ipfs/infrastructure#189
depends on ipfs/infrastructure#100

**Comment by daviddias** [comment]
@lgierth The new website has been merged and it needs to get deployed. Shall I do it manually? Or can you configure the automated builds? Thank you!

**Comment by ghost** [comment]
Yeah need to do it manually for now

**Comment by daviddias** [comment]
ok :)

**Comment by daviddias** [comment]
We now have the awesome makefile for super fast deploys!
