### ISSUE TITLE
Define which languages we want to list

### ISSUE THREAD

**Issue by victorb** [ipld/website#16]
Currently listed languages and state:

* JavaScript - Started implementation
* Go - Started implementation
* C - Soon starting
* Python - Soon starting

@nicola needs to define exactly what languages he wants listed on the website and in which state they are. @victorbjelkholm will make it more clear where you can contribute to each one of them

depends on ipld/ipld#9

**Comment by RichardLitt** [comment]
This information should also be in ipld/ipld's README.

**Comment by nicola** [comment]
- Go-IPLD
- js-IPLD
- C-IPLD (as work in progress)
- and put one extra block that says something of the type: like "coming soon", but different

**Comment by victorb** [comment]
> C-IPLD

Should link to https://github.com/kenCode-de/c-ipld I guess?

> and put one extra block that says something of the type: like "coming soon", but different

Not sure what you mean with this, you mean for the C-IPLD or as a separate block?

**Comment by nicola** [comment]
As a separate block!
There is JS, go, c, future languages

**Comment by RichardLitt** [comment]
Let's create an issue in ipld/ipld for suggesting a new implementation!

**Comment by victorb** [comment]
* [x] Extra block will be a question mark and link to the issue created from above, icon could possibly be a question mark

**Comment by victorb** [comment]
- [ ] Missing correct link, currently links to https://github.com/ipld/ipld/issues/9 but should be linking to the artifact of that completed issue
