### ISSUE TITLE
List of videos/talks about IPLD

### ISSUE THREAD

**Issue by victorb** [ipld/website#17]
We should list a couple of videos and/or talks about IPLD on the website.

**Comment by nicola** [comment]
This is the most recent (which is outdated really!) from @jbenet: https://www.infoq.com/presentations/data-ipfs-ipld

---

Are there others that I have missed @jbenet ?

**Comment by jbenet** [comment]
We should really have some talks on IPLD.

**Comment by victorb** [comment]
Hm, maybe if there is not even two recorded videos/talks, maybe skip the section on the landing page for now?

**Comment by victorb** [comment]
- [x] Remove section for now, create new issue about having a proper video for next generation of the website

**Comment by victorb** [comment]
New issue: https://github.com/ipld/ipld/issues/10

**Comment by kenCode-de** [comment]
@jbenet explained it pretty good here: 
https://youtu.be/CAfagNmIeOE?t=22m16s
