### ISSUE TITLE
Make the call-to-action stronger

### ISSUE THREAD

**Issue by victorb** [ipld/website#18]
We want people to contribute and join the community so we need to make the non-existing call-to-action stronger and better than ever before!

depends on #21
depends on #24

**Comment by victorb** [comment]
Ended up doing like this:

![selection_001](https://cloud.githubusercontent.com/assets/459764/20567486/245a38ca-b199-11e6-9b35-c9713e09121d.png)

@RichardLitt @nicola you think it's good enough for now?

**Comment by RichardLitt** [comment]
I'm not sure. Why is Getting Started there twice? What does Community link to? Can we update that initial sentence to have a better lede?

**Comment by victorb** [comment]
@RichardLitt "Home | Getting Started" is the navigation, hence the duplication. From our call, I understood we really want to push people towards that page, but if you feel strongly about it, we could have just the navigation or move the buttons down. What you think @nicola?

Community links to the section you spent some time writing yesterday, "Shape IPLD With Us", I'll change the name of the link.

**Comment by nicola** [comment]
I think the menu at the top is a bit redundant, there is no need to say "Home", since we are already in home, and there is no need to write "get started", since there is already a call to action later on.

I my opinion, the menu can be removed, "Get Started" like it is now and maybe "Read More" (with an arrow pointing down) instead of "Community", so that you can find out more by scrolling down?

--

on a side note, I don't think we should write anywhere in big "Inter-planetary Linked Data", (in the same way IPFS.io doesn't do it), this can appear later on in a section, or FAQ, where we link to IPFS or similar.

**Comment by victorb** [comment]
> I think the menu at the top is a bit redundant, there is no need to say "Home", since we are already in home, and there is no need to write "get started", since there is already a call to action later on.
>
> I my opinion, the menu can be removed, "Get Started" like it is now and maybe "Read More" (with an arrow pointing down) instead of "Community", so that you can find out more by scrolling down?

If we remove the navigation menu, the only sensible thing to do would be to put the content on the "Getting Started" together with the home page, having just one single page. Does that make sense?

> on a side note, I don't think we should write anywhere in big "Inter-planetary Linked Data", (in the same way IPFS.io doesn't do it), this can appear later on in a section, or FAQ, where we link to IPFS or similar.

I'll remove it.

**Comment by nicola** [comment]
The Getting started cannot be in this page, it would be a mess.

We can make the button "getting started" clear, and, in the other page, we can write "home", or make sure users can understand that there is another page. By having something like "ipld -> get started".

I think it is standard now to have the logo to be a link to the home page.

No?

**Comment by RichardLitt** [comment]
That is standard, yes. Having Home is a useful redundancy, though, and good for screen readers. I think we should keep it on pages that aren't home.

**Comment by victorb** [comment]
- [ ] Move menu to top right
- [ ] Menu should have "Home", "Tutorial", "Specification" and "Github" instead, remove mini-links
- [ ] Call to action would be in the hero-header at this point

**Comment by jbenet** [comment]
- Many websites show the current page you're on, underlined or highlighted in some way to indicate "this is where you are". The menus/navs should not change. either it has Home always, or never.
- I think we should make the design of this site in its totality, and have brainstorming / feedback sessions holistically. 
  - statements like "The Getting started cannot be in this page, it would be a mess." show me that people aren't considering it all together, _together_. Visual design by committee doesn't work. It's important to consider _the whole thing_. and while each of us may be considering _the whole thing_ in our individual minds, it's important to talk about _the same_ whole thing -- i.e. concretize it into some mockups that we can bring up feedback with.

@VictorBjelkholm are there mocks or screenshots to look at, all-together? may be a good way to collect feedback, or to meet + brainstorm over.

**Comment by jbenet** [comment]
Also, @nicola i know you've put a bunch of thought into this site and what you'd like to have. if you want to draw a site and what you would make, it may be useful feedback for @VictorBjelkholm. @VictorBjelkholm if you dont have mocks / lots of it yet, may be good to do that too. your time will be much saved if we all agree on a pretty _clear_, _close to pixel perfect_ design on paper first.

**Comment by jbenet** [comment]
(btw-- i really like how it's looking, @VictorBjelkholm !)

**Comment by nicola** [comment]
Hey @jbenet I will then!

@VictorBjelkholm, @RichardLitt and I have met weekly to discuss how it should look like, we did make choices all together (in the way that you are suggesting), and also we went together through a few stages (who is this for, what we want, how it should look).

Even that comment you are referring to, I think we went through discussing that during one of our calls. I think so far, we have given full trust to @VictorBjelkholm to come up with a great design that encompasses what we have discussed during the calls (or online)!

**Comment by jbenet** [comment]
Ahhh sorry, i wasnt part of those so i didn't know. i was worried the
thread here was people talking past each other-- nevermind, carry on!

**Comment by victorb** [comment]
@nicola I've pushed new version of the website with the changes I've talked about it, you can review it here: https://ipfs.io/ipfs/QmYk2g4fEoQCQ5iQmTUzrHgkZ5xAAxHFaYRkMSWrASuFCK/

@jbenet please feel free to review above as well :)

**Comment by nicola** [comment]
@VictorBjelkholm do you mind updating the text with the one we agreed upon next week?

**Comment by victorb** [comment]
@nicola 
> @VictorBjelkholm do you mind updating the text with the one we agreed upon next week?

I've updated "Getting Started" -> "Get Started" and updated the navigation links. Are you thinking about the introduction text? The "The IPLD Data Mode defines a simple JSON-based structure for all merkle-dags, and identifies a set of formats to encode the structure into"

In that case, I think we're waiting for https://github.com/ipld/website/issues/21

**Comment by victorb** [comment]
- [x] Change Background for "Get Started" button
- [ ] Change code example to #24
