### ISSUE TITLE
Write up the contribute/community section

### ISSUE THREAD

**Issue by victorb** [ipld/website#19]
Landing page have a contribute/community section in the bottom. We should write down what exactly we want here.

**Comment by RichardLitt** [comment]
### Help Shape IPLD

IPLD is a community driven, open source technology. There are many ways you can contribute by getting involved: you can help write the specification, code implementations and tools using IPLD, craft examples and tutorials, and join our regular product calls to discuss IPLD with us. 

Join us on GitHub at [ipld/ipld](https://github.com/ipld/ipld)!

**Comment by RichardLitt** [comment]
I think that covers everything I think we should say; very open, lists that there are many ways to help out, and points them to GitHub where we will answer any questions they have and point them to the right places for their specific needs. 

We could also add a link to: Twitter (@ipld?) and IRC #ipfs.

**Comment by victorb** [comment]
> Help Shape IPLD

@RichardLitt, is the meaning that "Help Shape IPLD" would be the title of the section instead of "Community"?

In general I like it, not sure if we should add Twitter but adding link to IRC is probably a good idea.

**Comment by victorb** [comment]
Added it to the website in the meanwhile with the new title "Help Shape IPLD": http://beta.ipld.io/#community

**Comment by RichardLitt** [comment]
Yeah. Or maybe: "Shape IPLD With Us".

**Comment by nicola** [comment]
I like the work "Community" too

**Comment by nicola** [comment]
"IPLD is an open source project from the IPFS community" (maybe?)

**Comment by victorb** [comment]
Personally I think people would find the section easiest to understand and find if we name it "Community". Usually when you want to contribute you're looking for a "Contribute" section or "Community" in my mind.

**Comment by RichardLitt** [comment]
Community works. Let's just call it that.

**Comment by nicola** [comment]
Both work!

**Comment by RichardLitt** [comment]
Title: Community.
Sentance: "IPLD is an open source project from the IPFS community".

**Comment by RichardLitt** [comment]
Reopen based on merge?
