### ISSUE TITLE
Repurpose Minimal Cayman Theme

### ISSUE THREAD

**Issue by RichardLitt** [ipld/website#2]
This is a tracking issue for installing the [minimal-cayman](//github.com/RichardLitt/minimal-cayman) theme, which will be used as a starting point for designing this. 
- [x] Edit `_config.yml`.
- [x] Edit `index.md`.
- [ ] Replace logo with your own logo.
  - [x] Remove old logo entirely, from `src/` and `assets`.
- [x] Replace favicon with your own favicon.
- [x] Edit `package.json` if you plan on using semver to save and deploy website.
- [x] Remove or edit CNAME.
- [ ] Deploy!
- [x] Edit this README to reflect current website.

**Comment by RichardLitt** [comment]
@dignifiedquire @lgierth Can you give me access?

**Comment by dignifiedquire** [comment]
@RichardLitt what access exactly are you missing?

**Comment by RichardLitt** [comment]
I couldn't push. @lgierth fixed it, I think, should be good now.

**Comment by RichardLitt** [comment]
@lgierth  Can you help me point the DNS for the website to the IPFS hash?
