### ISSUE TITLE
More delightful design for landing and getting started page

### ISSUE THREAD

**Issue by victorb** [ipld/website#20]
Currently, lots of text and not really nice-looking. We need to make it better. I'll come up with some ideas, post them here and tag relevant people for review. 

depends on #21

**Comment by victorb** [comment]
Suggestion from @RichardLitt: Maybe look at the font palette. See https://femmebot.github.io/google-type/ for examples of good pairing.

**Comment by nicola** [comment]
I am not a fan of too fancy fonts, I think this one should be the same font as the IPFS website

**Comment by victorb** [comment]
@nicola I agree and what's currently applied to the website is the same font as the IPFS website, "Brandon"

**Comment by nicola** [comment]
Maybe I was referring to to the Get Started?
(Sorry if it is the same, ha!)

It feels comic sansy in the ipld website..

**Comment by victorb** [comment]
Tasks missing to finish this:

- [X] hero-header on the landing page, title (possible tagline), menu and background color
- [ ] Get (colorful) set of icons, ping @em-ly about getting some from other designers

**Comment by nicola** [comment]
- [ ] ping nicola's friends for icons and illustrations
