### ISSUE TITLE
Content in the "Get Started" page (the tutorial)

### ISSUE THREAD

**Issue by victorb** [ipld/website#21]
We need to come up with the following things:
- story/narrative of content
- structure 
- simple examples that we bring into real examples
- how to model real-life applications, blog/forum/users and so on

**Deadline** Next wednesday, November 23, 2016

**Comment by RichardLitt** [comment]
### The narrative

Our audience should be comprised of protocol researchers and web developers looking to use something like JSON-LD (or, rather, looking exactly to use JSON-LD on IPFS) on p2p systems. There may be other groups, but I see those two as the main ones. Academics and developers (who are also archivists). 

I think we can pitch it accordingly: IPLD is JSONLD upgraded. This is the JSON-LD slogan:

> Data is messy and disconnected. JSON-LD organizes and connects it, creating a better Web.

I think something similar as a tagline would work: 

> Data is messy, disconnected, and location dependent. IPLD lets you organize, connect, and content address your data. Harness the power of JSON and linked data, while keeping the cryptographic guarantees and content-addressable features of Merkle DAGs.

May be a bit long, though. 

### Structure

I think the lede above, followed by an example. Looking over the spec again, I find it really readable. What would be great is if we could have a simple example with clickable hashes. For instance: 

```js
{
  "foo": {
    "bar": "/ipfs/QmUmg7BZC1YP1ca66rRtWKxpXp77WgVHrnv263JtDuvs2k", // not a link
    "baz": {"/": "/ipfs/QmUmg7BZC1YP1ca66rRtWKxpXp77WgVHrnv263JtDuvs2k"} // link
  }
}
```

Where, when you clock on `bar`'s value, which would be highlighted in purple (or some other color), it would go through to another object. I think this would be fairly easy to make, and instrumental in showing how Merkle-links work. 

Do you think that this would be simple enough to use? 

#### To Do List

Alternatively:

```js
{
  "todoTasks": {
    "writePaper": {
         "/": "/ipfs/QmUmg7BZC1YP1ca66rRtWKxpXp77WgVHrnv263JtDuvs2k"
     },
    "buyMilk": {
        "/": "/ipfs/QmUmg7BZC1YP1ca66rRtWKxpXp77WgVHrnv263JtDuvs2k"
    }
  }
}
```

Where `/ipfs/QmUmg7BZC1YP1ca66rRtWKxpXp77WgVHrnv263JtDuvs2k` points to:

```js
{
  "buyMilk": {
    "status": "undone",
    "notes": "get 1 gallon"
  }
}
```

We could have an example where we update one of the tasks, and the link changes and points to the old one (granted, mutability in the examples may be a bit much for the first one?).

**Comment by RichardLitt** [comment]
@nicola Want to have a call to talk about this, at some point this week?

**Comment by nicola** [comment]
@RichardLitt because of Thanksgiving I have been out until now, we can have a call tomorrow in the evening Boston time (8pm?)

**Comment by nicola** [comment]
This is my content description (actually similar to the current IPLD spec)

Along all of the following, there will be the same recurring example (this could be the TODO or something simple to explain)

- The basics (simple pimple)
  - A JSON
    - naming: Hashing the JSON
    - addressing: pathname to point inside the JSON (in-object traversal)
  - Two JSON
    - naming: hashing the two
    - merkle links: one directional links
    - addressing: pathname to point across JSON
  - Merkle DAG
    - Why Merkle?
    - Range verifiability (one hash to rule them all)
- IPLD (crifty crafty)
  - The Path Scheme
  - The libraries
  - CID and Different formats
  - Pro examples:
    - blockchain
    - file system
    - social network
- Future: From RDF to IPLD

**Comment by victorb** [comment]
@RichardLitt 
> Where, when you clock on bar's value, which would be highlighted in purple (or some other color), it would go through to another object. I think this would be fairly easy to make, and instrumental in showing how Merkle-links work.
>
> Do you think that this would be simple enough to use?

I think it's better to save this work until we have the Playground which I see would work somewhat like this, instead of getting into this version of the Getting Started page.

**Comment by RichardLitt** [comment]
@nicola That seems like it is all for the "Getting Started". What about my comments about the lede for the top of the page?

**Comment by victorb** [comment]
Tasks missing to finish this:

- [ ] @nicola go through and make your first draft, and then assign it to Richard to asynchronously go through and make it cohesive
- [ ] @victorbjelkholm to apply to website

**Comment by nicola** [comment]
See issue https://github.com/ipld/website/pull/27

**Comment by RichardLitt** [comment]
Opened in a PR here: https://github.com/ipld/website/pull/27
