### ISSUE TITLE
Fix SSL cert

### ISSUE THREAD

**Issue by pjz** [ipld/website#22]
You guys probably know this, but I couldn't find an issue for it: Currently Chrome gives a warning when you go to the site because it's using a cert with a common name of `ipfs.io` instead of the site's name `ipld.io`

depends on ipfs/infrastructure#203

**Comment by victorb** [comment]
@pjz thanks for reporting this! Currently we don't have https setup for ipld.io, so it's implicitly using the ipfs.io certs. I've opened an issue for fixing this here: https://github.com/ipfs/infrastructure/issues/203

**Comment by victorb** [comment]
FYI: Added "depends on ipfs/infrastructure#203" in the issue top comment, to be able to track dependencies

**Comment by daviddias** [comment]
now ∞% more secure with HTTPS https://ipld.io/ :D
