### ISSUE TITLE
Improving the lede for IPLD

### ISSUE THREAD

**Issue by RichardLitt** [ipld/website#23]
From https://github.com/ipld/website/issues/21:

### The narrative

Our audience should be comprised of protocol researchers and web developers looking to use something like JSON-LD (or, rather, looking exactly to use JSON-LD on IPFS) on p2p systems. There may be other groups, but I see those two as the main ones. Academics and developers (who are also archivists). 

I think we can pitch it accordingly: IPLD is JSONLD upgraded. This is the JSON-LD slogan:

> Data is messy and disconnected. JSON-LD organizes and connects it, creating a better Web.

I think something similar as a tagline would work: 

> Data is messy, disconnected, and location dependent. IPLD lets you organize, connect, and content address your data. Harness the power of JSON and linked data, while keeping the cryptographic guarantees and content-addressable features of Merkle DAGs.

May be a bit long, though.

**Comment by nicola** [comment]
Suggestions: 
- Avoid mentioning JSON-ld since it creates a bit of incomprehension and misunderstanding
- Avoid mentioning Merkle Dags (for some people they have no meaning)

General idea:
- Problems with current urls
- Instead, name things with hashes
- make it clear that this is the building block for decentralized applications (or distributing data in decentralized applications)

**Comment by RichardLitt** [comment]
> Links break when data moves. By pointing to data directly with hashes representing the data itself, instead of looking for where it was, you can find the data you want. IPLD helps you reference data in a distributed, decentralized, and permanent web.

Hard to say all of those things in something that is catchy. Might not need the last sentence. Thoughts, @nicola?

**Comment by RichardLitt** [comment]
@nicola?

**Comment by nicola** [comment]
My take is more the following: 

> IPLD is the building block for distributing data securely. Naming data with hashes, we provide immutability and cryptographic integrity so that anyone in the network can be helping distributing the data without being trusted.

**Comment by RichardLitt** [comment]
> IPLD is a building block for distributing data securely. By naming data with hashes, we provide immutability and cryptographic integrity so that anyone in the network can help distribute the data without being trusted.

Not sure about "the building block" - you need more than one. Maybe "an essential part of distr.."?

**Comment by nicola** [comment]
"a building block"?

**Comment by RichardLitt** [comment]
That works, I just wish there were more building blocks to reference.

**Comment by RichardLitt** [comment]
> IPLD provides immutability and cryptographic integrity by naming data with hashes, so that anyone in the network can help distribute data without needing to be trusted.

**Comment by nicola** [comment]
🎉
