### ISSUE TITLE
Beautification step 1

### ISSUE THREAD

**Issue by nicola** [ipld/website#25]
A couple of comments:

Top part
- Write IPLD in Helvetica bold?
- Remove underlining of Community?
- Make Community smaller?
- Adding more padding on the left and right of the Get Started button

Feature part
- let's find different images or ask someone to throw different ones
- make the description justified instead of centered, it is very difficult to read

Languages part
- Use smaller and colourful logos
- future languages soon and the interrogation mark are difficult to understand, we need to communicate that better

---

The above are my opinions, feel free to point out if there is something that doesn't work!

**Comment by victorb** [comment]
I think most of them makes sense except "Write IPLD in Helvetica bold?", we should try to stick with cross-platform fonts or fonts we can provide ourselves and have license for. I don't think we have license for using Helvetica.

**Comment by nicola** [comment]
I think Helvetica is a standard character supported in every computer and OS and of public domain, I might be wrong (this is what ipfs also uses, and that is mainly sans-serif default option

**Comment by victorb** [comment]
No, Helvetica only comes with OSX and is not public domain. ipfs.io might
use it, but unless included in the page, it'll default to the platforms
default font for sans-serif. If we want to make use of Helvetica, we should
purchase it.

*Victor Bjelkholm*
Software Engineer
Protocol Labs, Inc.
http://ipn.io | https://ipfs.io

**Comment by dignifiedquire** [comment]
Given the issues around font licenses, especially if put on ipfs, I would suggest to use something from http://fonts.google.com/ unless there is a strong reason not to. Some suggestions of very good fonts that could be used for ipld would be

- Roboto 
- Open Sans 
- Source Sans Pro
- Lato

They are all great fonts with heavy weights, in therms of design knowledge, behind them and are freely available without licensing issues.

**Comment by nicola** [comment]
Great! I didn't know, thanks for pointing this out @VictorBjelkholm!
Also, I realized that the current IPFS logo is "BrandonTextWeb-Regular" instead!
