### ISSUE TITLE
Should this be named website?

### ISSUE THREAD

**Issue by ghost** [ipld/website#3]
So it's consistent with ipfs/website and multiformats/website

**Comment by RichardLitt** [comment]
I think so!

**Comment by jbenet** [comment]
I thought so too. But then what if we have multiple websites? The
playground may be a website on its own

**Comment by dignifiedquire** [comment]
Lets rename it to website for now, if we have multiple websites we can name them after their domain.s

**Comment by RichardLitt** [comment]
Done and closed.
